[[Hayagriva]]
arch = "aarch64"
git-tree-sha1 = "f3dbb4204b50b49955b39585fc6a9a69b1a655a1"
os = "macos"

    [[Hayagriva.download]]
    sha256 = "6fa0aa6d75c31122adb4f20f46f33c949fbc3eebcac5ca91a56b1898b506aaa3"
    url = "https://github.com/JuliaBinaryWrappers/Hayagriva_jll.jl/releases/download/Hayagriva-v0.4.0+0/Hayagriva.v0.4.0.aarch64-apple-darwin.tar.gz"
[[Hayagriva]]
arch = "aarch64"
git-tree-sha1 = "0a49cd654b4a9f146cabacf24b41f10e7cc8762d"
libc = "glibc"
os = "linux"

    [[Hayagriva.download]]
    sha256 = "b9e428efe5e1bb7c85dd04e11f9157aa527acd2d8c135d564a69f0432d94a95f"
    url = "https://github.com/JuliaBinaryWrappers/Hayagriva_jll.jl/releases/download/Hayagriva-v0.4.0+0/Hayagriva.v0.4.0.aarch64-linux-gnu.tar.gz"
[[Hayagriva]]
arch = "aarch64"
git-tree-sha1 = "fc437cd7a9b738599a0d1d682c34f92c5990b3e0"
libc = "musl"
os = "linux"

    [[Hayagriva.download]]
    sha256 = "17498a4714d9088f81fcf0f951a15f9209a61d23a1641d1579bd6c2abdd3f0b8"
    url = "https://github.com/JuliaBinaryWrappers/Hayagriva_jll.jl/releases/download/Hayagriva-v0.4.0+0/Hayagriva.v0.4.0.aarch64-linux-musl.tar.gz"
[[Hayagriva]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5676395d090587c86adddc2f4264eff52e74af10"
libc = "glibc"
os = "linux"

    [[Hayagriva.download]]
    sha256 = "113b91b63b92d626016d1c6d4b8f1affa4af522d431d3f010f5fcd186c3f9319"
    url = "https://github.com/JuliaBinaryWrappers/Hayagriva_jll.jl/releases/download/Hayagriva-v0.4.0+0/Hayagriva.v0.4.0.armv6l-linux-gnueabihf.tar.gz"
[[Hayagriva]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "48fb12db5628e0fc138a69e025c941eb0b57fe06"
libc = "musl"
os = "linux"

    [[Hayagriva.download]]
    sha256 = "a5f4d2505501849d7ff538c78b4c5c03fc7147c17d6805e0ea5ccdf46a528050"
    url = "https://github.com/JuliaBinaryWrappers/Hayagriva_jll.jl/releases/download/Hayagriva-v0.4.0+0/Hayagriva.v0.4.0.armv6l-linux-musleabihf.tar.gz"
[[Hayagriva]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "17fb691bf6c8852dfa749aec6cee53010f1946aa"
libc = "glibc"
os = "linux"

    [[Hayagriva.download]]
    sha256 = "ff2dd414ab023d9d4d6b9b343da30eb94eb99288520a40dea32d3c98891eba36"
    url = "https://github.com/JuliaBinaryWrappers/Hayagriva_jll.jl/releases/download/Hayagriva-v0.4.0+0/Hayagriva.v0.4.0.armv7l-linux-gnueabihf.tar.gz"
[[Hayagriva]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ab3690185aaf29118a7c10d9e3b1105054b4aa98"
libc = "musl"
os = "linux"

    [[Hayagriva.download]]
    sha256 = "bbbaa7d821aa5a8132e156bb8848c4d5d2521617f112d9c4c39cf946566702e7"
    url = "https://github.com/JuliaBinaryWrappers/Hayagriva_jll.jl/releases/download/Hayagriva-v0.4.0+0/Hayagriva.v0.4.0.armv7l-linux-musleabihf.tar.gz"
[[Hayagriva]]
arch = "i686"
git-tree-sha1 = "4106427ed6961022f666812dce36c020a9392160"
libc = "glibc"
os = "linux"

    [[Hayagriva.download]]
    sha256 = "76029d288f9c3a4e960be7fc047bc6672a7e21860a001276c486ba979e6ef091"
    url = "https://github.com/JuliaBinaryWrappers/Hayagriva_jll.jl/releases/download/Hayagriva-v0.4.0+0/Hayagriva.v0.4.0.i686-linux-gnu.tar.gz"
[[Hayagriva]]
arch = "i686"
git-tree-sha1 = "b2dc0e6ccd90ad9e33f11aaca3b983120a0bd215"
libc = "musl"
os = "linux"

    [[Hayagriva.download]]
    sha256 = "6d764aae8c247f8285fb0ce098966432012a460189eb51fc5b21ac07fd25a827"
    url = "https://github.com/JuliaBinaryWrappers/Hayagriva_jll.jl/releases/download/Hayagriva-v0.4.0+0/Hayagriva.v0.4.0.i686-linux-musl.tar.gz"
[[Hayagriva]]
arch = "powerpc64le"
git-tree-sha1 = "7ddc4a92d5b768c67ce209c6cb947c16e390596f"
libc = "glibc"
os = "linux"

    [[Hayagriva.download]]
    sha256 = "28373bc8ceb6494b11789afa112231bb018e8b0c3f96dfe4f05815d9a243b56e"
    url = "https://github.com/JuliaBinaryWrappers/Hayagriva_jll.jl/releases/download/Hayagriva-v0.4.0+0/Hayagriva.v0.4.0.powerpc64le-linux-gnu.tar.gz"
[[Hayagriva]]
arch = "x86_64"
git-tree-sha1 = "5dd4bdf957b35b6679f94b9db486cb1ab4d68049"
os = "macos"

    [[Hayagriva.download]]
    sha256 = "d14699300c6d64a74a26480cc780a0f5c8b0f9081812028566fd8f8688563d4f"
    url = "https://github.com/JuliaBinaryWrappers/Hayagriva_jll.jl/releases/download/Hayagriva-v0.4.0+0/Hayagriva.v0.4.0.x86_64-apple-darwin.tar.gz"
[[Hayagriva]]
arch = "x86_64"
git-tree-sha1 = "eb9a3367cc5e0959b0ba6469b504983aec852c44"
libc = "glibc"
os = "linux"

    [[Hayagriva.download]]
    sha256 = "6003a106997a977d1c910208ccff6c13ab8be15e7f45d078a9bddfedc3e4a820"
    url = "https://github.com/JuliaBinaryWrappers/Hayagriva_jll.jl/releases/download/Hayagriva-v0.4.0+0/Hayagriva.v0.4.0.x86_64-linux-gnu.tar.gz"
[[Hayagriva]]
arch = "x86_64"
git-tree-sha1 = "5f9dbec0141a21da361d020fb09f46cf5e978780"
libc = "musl"
os = "linux"

    [[Hayagriva.download]]
    sha256 = "26dfc353860be72219618dbd06cd1aeda9268cfabea91e65b5b7993184c4b9eb"
    url = "https://github.com/JuliaBinaryWrappers/Hayagriva_jll.jl/releases/download/Hayagriva-v0.4.0+0/Hayagriva.v0.4.0.x86_64-linux-musl.tar.gz"
[[Hayagriva]]
arch = "x86_64"
git-tree-sha1 = "e5d1c4db1d454c08e73de1b1f8f682f5f56767d9"
os = "freebsd"

    [[Hayagriva.download]]
    sha256 = "cff950435b6875470ccb862773b92298669543eaead6431988e4d70f16c056f8"
    url = "https://github.com/JuliaBinaryWrappers/Hayagriva_jll.jl/releases/download/Hayagriva-v0.4.0+0/Hayagriva.v0.4.0.x86_64-unknown-freebsd.tar.gz"
[[Hayagriva]]
arch = "x86_64"
git-tree-sha1 = "7ded5fc40bc127fbc063b215f0748bf099be91d1"
os = "windows"

    [[Hayagriva.download]]
    sha256 = "c020508f83ce472a595e3f443e71f06b49b729674c71df342abeb29bb65f6faa"
    url = "https://github.com/JuliaBinaryWrappers/Hayagriva_jll.jl/releases/download/Hayagriva-v0.4.0+0/Hayagriva.v0.4.0.x86_64-w64-mingw32.tar.gz"
